# Generated by Django 6.0.3 on 2026-03-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, help_text='Book author', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='battery_health',
            field=models.CharField(blank=True, help_text='e.g. 87%', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='bill_available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='e.g. Apple, Samsung, Dell, Nike', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='call_enabled',
            field=models.BooleanField(default=False, help_text='Allow buyers to call'),
        ),
        migrations.AddField(
            model_name='product',
            name='chat_enabled',
            field=models.BooleanField(default=True, help_text='Allow buyers to chat'),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='edition',
            field=models.CharField(blank=True, help_text='Book edition', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, help_text='e.g. Intel i5 12th Gen', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, help_text='e.g. 8 GB', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='reason_for_selling',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_name',
            field=models.CharField(blank=True, help_text='Contact name', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, help_text='e.g. 256 GB SSD', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_available',
            field=models.BooleanField(default=False),
        ),
    ]
